FROM node:20.11.1 AS development

RUN mkdir -p /home/app
RUN chown node /home/app

WORKDIR /home/app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]