http:
  port: 5000
admin:
  port: 9876
  host: localhost

apiEndpoints:
  vitrinaProductos:
    host: "caballo.thenexusbattlesii.online"
    paths: "*"
  carroCompras:
    host: "dragon.thenexusbattlesii.online"
    paths: "*"
  manejoUsuarios:
    host: "conejo.thenexusbattlesii.online"
    paths: "*"
  portalPagos:
    host: "serpiente.thenexusbattlesii.online"
    paths: "*"
  inventario:
    host: "mono.thenexusbattlesii.online"
    paths: "*"
  listaDeseos:
    host: "cabra.thenexusbattlesii.online"
    paths: "*"

serviceEndpoints:
  vitrinaProductosService:
    url: "http://caballo.thenexusbattlesii.online:14443"
  carroComprasService:
    url: "http://dragon.thenexusbattlesii.online:5443"
  manejoUsuariosService:
    url: "http://conejo.thenexusbattlesii.online:4443"
  portalPagosService:
    url: "http://serpiente.thenexusbattlesii.online:13443"
  inventarioService:
    url: "http://mono.thenexusbattlesii.online:8443"
  listaDeseosService:
    url: "http://cabra.thenexusbattlesii.online:12443"

policies:
  - proxy

pipelines:
  - name: default
    apiEndpoints:
      - vitrinaProductos
      - carroCompras
      - manejoUsuarios
      - portalPagos
      - inventario
      - listaDeseos
    policies:
      - proxy:
          - action:
              serviceEndpoint: vitrinaProductosService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: carroComprasService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: manejoUsuariosService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: portalPagosService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: inventarioService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: listaDeseosService
              changeOrigin: true
