https:
  port: 5000
  tls:
    "*.thenexusbattlesii.online":
      key: ./certs/privkey.pem
      cert: ./certs/cert.pem
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api1:
    host: "*"
    paths: "/usuario/*"
  api:
    host: "*"
    paths: "/*"

serviceEndpoints:
  vitrinaProductosService:
    url: "https://caballo.thenexusbattlesii.online:4000"
  carroComprasService:
    url: "https://dragon.thenexusbattlesii.online:4000"
  manejoUsuariosService:
    url: "https://conejo.thenexusbattlesii.online:4000"
  portalPagosService:
    url: "https://serpiente.thenexusbattlesii.online:4000"
  inventarioService:
    url: "https://mono.thenexusbattlesii.online:4000"
  listaDeseosService:
    url: "https://cabra.thenexusbattlesii.online:4000"

policies:
  - proxy
  - jwt
  - request-transformer

pipelines:
  pipeline_1:
    apiEndpoints:
      - api
    policies:
      - jwt:
          - action:
              secretOrPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCJvA2NnE7PAKYrEDafXpOOQp0yahOhKXgPpRA5BUtOpTmVOmRhmTSKKQPJ8CXsCu6TM9TOQxKrIpZcyRe44zpq39sQGDDbmUpUXWv3Sq/qDaHY2REaCccXZpZPOx5cGTuKTX9uGxi9SKm8+quYSa1FYHWde47CDfSs88gsBsYngQIDAQAB
              checkCredentialExistence: false
      - request-transformer:
          - action:
              body:
                add:
                  user: "req.user"
      - proxy:
          - condition:
              name: pathMatch
              pattern: "/vitrina"
            action:
              serviceEndpoint: vitrinaProductosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/carro"
            action:
              serviceEndpoint: carroComprasService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/usuario"
            action:
              serviceEndpoint: manejoUsuariosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/pagos"
            action:
              serviceEndpoint: portalPagosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/inventario"
            action:
              serviceEndpoint: inventarioService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/deseos"
            action:
              serviceEndpoint: listaDeseosService
              changeOrigin: true

  pipeline_2:
    apiEndpoints:
      - api1
    policies:
      - proxy:
          - action:
              serviceEndpoint: manejoUsuariosService
              changeOrigin: true
