http:
  port: 5000
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: "*"
    paths: "/*"

serviceEndpoints:
  firstService:
    url: "http://back:3000"
  secondService:
    url: "http://back1:3000"

policies:
  - proxy

pipelines:
  pipeline_1:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - condition:
              name: pathMatch
              pattern: "/carro*"
            action:
              serviceEndpoint: firstService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/orden*"
            action:
              serviceEndpoint: secondService
              changeOrigin: true
