http:
  port: 5000
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api1:
    host: "*"
    paths: "/usuario/logIn"
  api:
    host: "*"
    paths: "/*"

serviceEndpoints:
  vitrinaProductosService:
    url: "http://caballo.thenexusbattlesii.online:4000"
  carroComprasService:
    url: "http://dragon.thenexusbattlesii.online:4000"
  manejoUsuariosService:
    url: "http://conejo.thenexusbattlesii.online:4000"
  portalPagosService:
    url: "http://serpiente.thenexusbattlesii.online:4000"
  inventarioService:
    url: "http://mono.thenexusbattlesii.online:4000"
  listaDeseosService:
    url: "http://cabra.thenexusbattlesii.online:4000"

policies:
  - proxy
  - jwt

pipelines:
  pipeline_1:
    apiEndpoints:
      - api
    policies:
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET-"mySecret"}
      - proxy:
          - condition:
              name: pathMatch
              pattern: "/vitrina"
            action:
              serviceEndpoint: vitrinaProductosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/carro"
            action:
              serviceEndpoint: carroComprasService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/usuario"
            action:
              serviceEndpoint: manejoUsuariosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/pagos"
            action:
              serviceEndpoint: portalPagosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/inventario"
            action:
              serviceEndpoint: inventarioService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/deseos"
            action:
              serviceEndpoint: listaDeseosService
              changeOrigin: true
  pipeline_2:
    apiEndpoints:
      - api1
    policies:
      - proxy:
          - action:
              serviceEndpoint: manejoUsuariosService
              changeOrigin: true
