http:
  port: 5000
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: "*"
    paths: "/*"

serviceEndpoints:
  vitrinaProductosService:
    url: "http://caballo.thenexusbattlesii.online:14443"
  carroComprasService:
    url: "http://dragon.thenexusbattlesii.online:5443"
  manejoUsuariosService:
    url: "http://conejo.thenexusbattlesii.online:4443"
  portalPagosService:
    url: "http://serpiente.thenexusbattlesii.online:13443"
  inventarioService:
    url: "http://mono.thenexusbattlesii.online:8443"
  listaDeseosService:
    url: "http://cabra.thenexusbattlesii.online:12443"

policies:
  - proxy

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - condition:
              name: pathMatch
              pattern: "/vitrina"
            action:
              serviceEndpoint: vitrinaProductosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/carro"
            action:
              serviceEndpoint: carroComprasService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/usuario"
            action:
              serviceEndpoint: manejoUsuariosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/pagos"
            action:
              serviceEndpoint: portalPagosService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/inventario"
            action:
              serviceEndpoint: inventarioService
              changeOrigin: true
          - condition:
              name: pathMatch
              pattern: "/deseos"
            action:
              serviceEndpoint: listaDeseosService
              changeOrigin: true
